name: 'Manage FUNDING.yml for Wishlist Projects'
description: 'Automatically creates or updates FUNDING.yml in wishlist projects with wishlist link'
author: 'oss-wishlist'

inputs:
  github-token:
    description: 'GitHub token (PAT from bot account or personal account) with public_repo scope'
    required: true
  cache-url:
    description: 'URL to refresh wishlist cache (optional)'
    required: false
    default: 'https://urchin-app-bozjb.ondigitalocean.app/api/wishlists?refresh=true'

outputs:
  pr-url:
    description: 'URL of the created or updated PR'
  status:
    description: 'Status of the action (success, skipped, error)'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'heart'
  color: 'purple'
