# Workflow template for oss-wishlist/wishlists repository
# Copy this to: .github/workflows/manage-funding-yml.yml

name: Manage Wishlist Actions

on:
  issues:
    types: [opened, labeled]

jobs:
  manage-wishlist:
    # Only run for issues with the 'funding-yml-requested' label
    if: contains(github.event.issue.labels.*.name, 'funding-yml-requested')
    runs-on: ubuntu-latest
    
    permissions:
      issues: write        # To add labels and comments to wishlists issues
      contents: read       # To read repository content
      
    steps:
      - name: Manage Wishlist Actions
        uses: oss-wishlist/manage-funding-yml@v1
        with:
          # IMPORTANT: Use a PAT with 'public_repo' scope stored in secrets
          # The default GITHUB_TOKEN cannot create PRs in other repositories
          github-token: ${{ secrets.WISHLIST_BOT_TOKEN }}
          # Optional: URL to refresh wishlist cache after PR creation
          # Default is staging URL, change to production when ready
          cache-url: 'https://urchin-app-bozjb.ondigitalocean.app/api/wishlists?refresh=true'
